apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-html-app-secrets
  namespace: test-html-app
  labels:
    app: test-html-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: test-html-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: harumi/test-html-app/dev
        property: api_key
    - secretKey: DATABASE_URL
      remoteRef:
        key: harumi/test-html-app/dev
        property: database_url